# /usr/bin/env python
import pygtk,gtk

button=gtk.Button()
button2=gtk.Button()
button3=gtk.Button()
button4=gtk.Button()
image=gtk.Image()
image.set_from_file("out.png")
image.set_size_request(400,400)
label=gtk.Label("Python")
hbox=gtk.HBox()
hbox.pack_start(image)
hbox.pack_start(label)
button.add(hbox)
hbox.pack_start(button2)
button2.add(hbox)
button3.add(hbox)
button4.add(hbox)
vbox=gtk.VBox()
vbox.pack_start(button)
win=gtk.Window()
win.add(vbox)
win.show_all()
win.set_size_request(650,500)
win.connect("destroy",lambda wid:gtk.main_quit())
gtk.main()
