/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_rat__n (void)
{
  GtkWidget *rat__n;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *open1;
  GtkWidget *save_as1;
  GtkWidget *separator2;
  GtkWidget *quit1;
  GtkWidget *transforms1;
  GtkWidget *transforms1_menu;
  GtkWidget *reset1;
  GtkWidget *separator8;
  GtkWidget *x_axis1;
  GtkWidget *x_axis1_menu;
  GtkWidget *linearX;
  GtkWidget *steppedX;
  GtkWidget *randomX;
  GtkWidget *sineX;
  GtkWidget *y_axis1;
  GtkWidget *y_axis1_menu;
  GtkWidget *linearY;
  GtkWidget *steppedY;
  GtkWidget *randomY;
  GtkWidget *sineY;
  GtkWidget *separator1;
  GtkWidget *editcrv;
  GtkWidget *editcrv_menu;
  GtkWidget *customX;
  GtkWidget *customY;
  GtkWidget *separator11;
  GtkWidget *preferences;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *drawingarea1;
  GtkWidget *hseparator1;
  GtkWidget *hbox2;
  GtkWidget *vbox4;
  GtkWidget *label5;
  GtkWidget *hbox3;
  GtkWidget *label6;
  GtkObject *controllerXspin_adj;
  GtkWidget *controllerXspin;
  GtkWidget *hbox8;
  GtkWidget *invertx;
  GtkWidget *reverseX;
  GtkWidget *hbox6;
  GtkWidget *label13;
  GtkObject *chanX_adj;
  GtkWidget *chanX;
  GtkWidget *vseparator1;
  GtkWidget *vbox5;
  GtkWidget *label8;
  GtkWidget *hbox4;
  GtkWidget *label9;
  GtkObject *controllerYspin_adj;
  GtkWidget *controllerYspin;
  GtkWidget *hbox9;
  GtkWidget *invertY;
  GtkWidget *reverseY;
  GtkWidget *hbox7;
  GtkWidget *label14;
  GtkObject *chanY_adj;
  GtkWidget *chanY;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  rat__n = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (rat__n), "ratón");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (rat__n), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic ("_File");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), open1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save_as1);

  separator2 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);

  transforms1 = gtk_menu_item_new_with_mnemonic ("_Transforms");
  gtk_widget_show (transforms1);
  gtk_container_add (GTK_CONTAINER (menubar1), transforms1);

  transforms1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (transforms1), transforms1_menu);

  reset1 = gtk_menu_item_new_with_mnemonic ("Reset");
  gtk_widget_show (reset1);
  gtk_container_add (GTK_CONTAINER (transforms1_menu), reset1);

  separator8 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator8);
  gtk_container_add (GTK_CONTAINER (transforms1_menu), separator8);
  gtk_widget_set_sensitive (separator8, FALSE);

  x_axis1 = gtk_menu_item_new_with_mnemonic ("X preset");
  gtk_widget_show (x_axis1);
  gtk_container_add (GTK_CONTAINER (transforms1_menu), x_axis1);

  x_axis1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (x_axis1), x_axis1_menu);

  linearX = gtk_menu_item_new_with_mnemonic ("Linear");
  gtk_widget_show (linearX);
  gtk_container_add (GTK_CONTAINER (x_axis1_menu), linearX);

  steppedX = gtk_menu_item_new_with_mnemonic ("Stepped");
  gtk_widget_show (steppedX);
  gtk_container_add (GTK_CONTAINER (x_axis1_menu), steppedX);

  randomX = gtk_menu_item_new_with_mnemonic ("Random");
  gtk_widget_show (randomX);
  gtk_container_add (GTK_CONTAINER (x_axis1_menu), randomX);

  sineX = gtk_menu_item_new_with_mnemonic ("Sine");
  gtk_widget_show (sineX);
  gtk_container_add (GTK_CONTAINER (x_axis1_menu), sineX);

  y_axis1 = gtk_menu_item_new_with_mnemonic ("Y preset");
  gtk_widget_show (y_axis1);
  gtk_container_add (GTK_CONTAINER (transforms1_menu), y_axis1);

  y_axis1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (y_axis1), y_axis1_menu);

  linearY = gtk_menu_item_new_with_mnemonic ("Linear");
  gtk_widget_show (linearY);
  gtk_container_add (GTK_CONTAINER (y_axis1_menu), linearY);

  steppedY = gtk_menu_item_new_with_mnemonic ("Stepped");
  gtk_widget_show (steppedY);
  gtk_container_add (GTK_CONTAINER (y_axis1_menu), steppedY);

  randomY = gtk_menu_item_new_with_mnemonic ("Random");
  gtk_widget_show (randomY);
  gtk_container_add (GTK_CONTAINER (y_axis1_menu), randomY);

  sineY = gtk_menu_item_new_with_mnemonic ("Sine");
  gtk_widget_show (sineY);
  gtk_container_add (GTK_CONTAINER (y_axis1_menu), sineY);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (transforms1_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  editcrv = gtk_menu_item_new_with_mnemonic ("Edit");
  gtk_widget_show (editcrv);
  gtk_container_add (GTK_CONTAINER (transforms1_menu), editcrv);

  editcrv_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (editcrv), editcrv_menu);

  customX = gtk_menu_item_new_with_mnemonic ("X axis curve");
  gtk_widget_show (customX);
  gtk_container_add (GTK_CONTAINER (editcrv_menu), customX);

  customY = gtk_menu_item_new_with_mnemonic ("Y axis curve");
  gtk_widget_show (customY);
  gtk_container_add (GTK_CONTAINER (editcrv_menu), customY);

  separator11 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator11);
  gtk_container_add (GTK_CONTAINER (transforms1_menu), separator11);
  gtk_widget_set_sensitive (separator11, FALSE);

  preferences = gtk_image_menu_item_new_from_stock ("gtk-preferences", accel_group);
  gtk_widget_show (preferences);
  gtk_container_add (GTK_CONTAINER (transforms1_menu), preferences);

  menuitem4 = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_menu_item_new_with_mnemonic ("_About");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  drawingarea1 = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea1);
  gtk_box_pack_start (GTK_BOX (vbox1), drawingarea1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (drawingarea1, 256, 256);
  gtk_widget_set_events (drawingarea1, GDK_POINTER_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_KEY_PRESS_MASK | GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox4, TRUE, FALSE, 0);

  label5 = gtk_label_new ("X");
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (vbox4), label5, FALSE, FALSE, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox3, FALSE, FALSE, 0);

  label6 = gtk_label_new ("Controller");
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label6), 5, 0);

  controllerXspin_adj = gtk_adjustment_new (1, 0, 127, 1, 10, 10);
  controllerXspin = gtk_spin_button_new (GTK_ADJUSTMENT (controllerXspin_adj), 1, 0);
  gtk_widget_show (controllerXspin);
  gtk_box_pack_start (GTK_BOX (hbox3), controllerXspin, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (controllerXspin), TRUE);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox8, FALSE, FALSE, 0);

  invertx = gtk_check_button_new_with_mnemonic ("Invert");
  gtk_widget_show (invertx);
  gtk_box_pack_start (GTK_BOX (hbox8), invertx, FALSE, FALSE, 0);

  reverseX = gtk_check_button_new_with_mnemonic ("Reverse");
  gtk_widget_show (reverseX);
  gtk_box_pack_start (GTK_BOX (hbox8), reverseX, FALSE, FALSE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox6, FALSE, FALSE, 0);

  label13 = gtk_label_new ("Channel");
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox6), label13, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label13), 3, 0);

  chanX_adj = gtk_adjustment_new (1, 1, 16, 1, 10, 10);
  chanX = gtk_spin_button_new (GTK_ADJUSTMENT (chanX_adj), 1, 0);
  gtk_widget_show (chanX);
  gtk_box_pack_start (GTK_BOX (hbox6), chanX, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (chanX), TRUE);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_box_pack_start (GTK_BOX (hbox2), vseparator1, FALSE, TRUE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox5, TRUE, FALSE, 0);

  label8 = gtk_label_new ("Y");
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox5), label8, FALSE, FALSE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox4, FALSE, FALSE, 0);

  label9 = gtk_label_new ("Controller");
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label9), 5, 0);

  controllerYspin_adj = gtk_adjustment_new (1, 0, 127, 1, 10, 10);
  controllerYspin = gtk_spin_button_new (GTK_ADJUSTMENT (controllerYspin_adj), 1, 0);
  gtk_widget_show (controllerYspin);
  gtk_box_pack_start (GTK_BOX (hbox4), controllerYspin, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (controllerYspin), TRUE);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox9, FALSE, FALSE, 0);

  invertY = gtk_check_button_new_with_mnemonic ("Invert");
  gtk_widget_show (invertY);
  gtk_box_pack_start (GTK_BOX (hbox9), invertY, FALSE, FALSE, 0);

  reverseY = gtk_check_button_new_with_mnemonic ("Reverse");
  gtk_widget_show (reverseY);
  gtk_box_pack_start (GTK_BOX (hbox9), reverseY, FALSE, FALSE, 0);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox7, FALSE, FALSE, 0);

  label14 = gtk_label_new ("Channel");
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox7), label14, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label14), 3, 0);

  chanY_adj = gtk_adjustment_new (2, 1, 16, 1, 10, 10);
  chanY = gtk_spin_button_new (GTK_ADJUSTMENT (chanY_adj), 1, 0);
  gtk_widget_show (chanY);
  gtk_box_pack_start (GTK_BOX (hbox7), chanY, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (chanY), TRUE);

  g_signal_connect ((gpointer) rat__n, "delete_event",
                    G_CALLBACK (on_ralphwindow_delete_event),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) reset1, "activate",
                    G_CALLBACK (on_reset1_activate),
                    NULL);
  g_signal_connect ((gpointer) linearX, "activate",
                    G_CALLBACK (on_linearX_activate),
                    NULL);
  g_signal_connect ((gpointer) steppedX, "activate",
                    G_CALLBACK (on_steppedX_activate),
                    NULL);
  g_signal_connect ((gpointer) randomX, "activate",
                    G_CALLBACK (on_randomX_activate),
                    NULL);
  g_signal_connect ((gpointer) sineX, "activate",
                    G_CALLBACK (on_sineX_activate),
                    NULL);
  g_signal_connect ((gpointer) linearY, "activate",
                    G_CALLBACK (on_linearY_activate),
                    NULL);
  g_signal_connect ((gpointer) steppedY, "activate",
                    G_CALLBACK (on_steppedY_activate),
                    NULL);
  g_signal_connect ((gpointer) randomY, "activate",
                    G_CALLBACK (on_randomY_activate),
                    NULL);
  g_signal_connect ((gpointer) sineY, "activate",
                    G_CALLBACK (on_sineY_activate),
                    NULL);
  g_signal_connect ((gpointer) customX, "activate",
                    G_CALLBACK (on_customX_activate),
                    NULL);
  g_signal_connect ((gpointer) customY, "activate",
                    G_CALLBACK (on_customY_activate),
                    NULL);
  g_signal_connect ((gpointer) preferences, "activate",
                    G_CALLBACK (on_preferences_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "button_press_event",
                    G_CALLBACK (on_drawingarea1_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "button_release_event",
                    G_CALLBACK (on_drawingarea1_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "motion_notify_event",
                    G_CALLBACK (on_drawingarea1_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "size_allocate",
                    G_CALLBACK (on_drawingarea1_size_allocate),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "key_press_event",
                    G_CALLBACK (on_drawingarea1_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "expose_event",
                    G_CALLBACK (on_drawingarea1_expose_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "leave_notify_event",
                    G_CALLBACK (on_drawingarea1_leave_notify_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "configure_event",
                    G_CALLBACK (on_drawingarea1_configure_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "enter_notify_event",
                    G_CALLBACK (on_drawingarea1_enter_notify_event),
                    NULL);
  g_signal_connect ((gpointer) controllerXspin, "value_changed",
                    G_CALLBACK (on_controllerXspin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) invertx, "clicked",
                    G_CALLBACK (on_invertx_clicked),
                    NULL);
  g_signal_connect ((gpointer) reverseX, "clicked",
                    G_CALLBACK (on_reverseX_clicked),
                    NULL);
  g_signal_connect ((gpointer) chanX, "value_changed",
                    G_CALLBACK (on_chanX_value_changed),
                    NULL);
  g_signal_connect ((gpointer) controllerYspin, "value_changed",
                    G_CALLBACK (on_controllerYspin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) invertY, "clicked",
                    G_CALLBACK (on_invertY_clicked),
                    NULL);
  g_signal_connect ((gpointer) reverseY, "clicked",
                    G_CALLBACK (on_reverseY_clicked),
                    NULL);
  g_signal_connect ((gpointer) chanY, "value_changed",
                    G_CALLBACK (on_chanY_value_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rat__n, rat__n, "rat__n");
  GLADE_HOOKUP_OBJECT (rat__n, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (rat__n, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (rat__n, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (rat__n, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (rat__n, open1, "open1");
  GLADE_HOOKUP_OBJECT (rat__n, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (rat__n, separator2, "separator2");
  GLADE_HOOKUP_OBJECT (rat__n, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (rat__n, transforms1, "transforms1");
  GLADE_HOOKUP_OBJECT (rat__n, transforms1_menu, "transforms1_menu");
  GLADE_HOOKUP_OBJECT (rat__n, reset1, "reset1");
  GLADE_HOOKUP_OBJECT (rat__n, separator8, "separator8");
  GLADE_HOOKUP_OBJECT (rat__n, x_axis1, "x_axis1");
  GLADE_HOOKUP_OBJECT (rat__n, x_axis1_menu, "x_axis1_menu");
  GLADE_HOOKUP_OBJECT (rat__n, linearX, "linearX");
  GLADE_HOOKUP_OBJECT (rat__n, steppedX, "steppedX");
  GLADE_HOOKUP_OBJECT (rat__n, randomX, "randomX");
  GLADE_HOOKUP_OBJECT (rat__n, sineX, "sineX");
  GLADE_HOOKUP_OBJECT (rat__n, y_axis1, "y_axis1");
  GLADE_HOOKUP_OBJECT (rat__n, y_axis1_menu, "y_axis1_menu");
  GLADE_HOOKUP_OBJECT (rat__n, linearY, "linearY");
  GLADE_HOOKUP_OBJECT (rat__n, steppedY, "steppedY");
  GLADE_HOOKUP_OBJECT (rat__n, randomY, "randomY");
  GLADE_HOOKUP_OBJECT (rat__n, sineY, "sineY");
  GLADE_HOOKUP_OBJECT (rat__n, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (rat__n, editcrv, "editcrv");
  GLADE_HOOKUP_OBJECT (rat__n, editcrv_menu, "editcrv_menu");
  GLADE_HOOKUP_OBJECT (rat__n, customX, "customX");
  GLADE_HOOKUP_OBJECT (rat__n, customY, "customY");
  GLADE_HOOKUP_OBJECT (rat__n, separator11, "separator11");
  GLADE_HOOKUP_OBJECT (rat__n, preferences, "preferences");
  GLADE_HOOKUP_OBJECT (rat__n, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (rat__n, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (rat__n, about1, "about1");
  GLADE_HOOKUP_OBJECT (rat__n, drawingarea1, "drawingarea1");
  GLADE_HOOKUP_OBJECT (rat__n, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (rat__n, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (rat__n, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (rat__n, label5, "label5");
  GLADE_HOOKUP_OBJECT (rat__n, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (rat__n, label6, "label6");
  GLADE_HOOKUP_OBJECT (rat__n, controllerXspin, "controllerXspin");
  GLADE_HOOKUP_OBJECT (rat__n, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (rat__n, invertx, "invertx");
  GLADE_HOOKUP_OBJECT (rat__n, reverseX, "reverseX");
  GLADE_HOOKUP_OBJECT (rat__n, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (rat__n, label13, "label13");
  GLADE_HOOKUP_OBJECT (rat__n, chanX, "chanX");
  GLADE_HOOKUP_OBJECT (rat__n, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (rat__n, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (rat__n, label8, "label8");
  GLADE_HOOKUP_OBJECT (rat__n, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (rat__n, label9, "label9");
  GLADE_HOOKUP_OBJECT (rat__n, controllerYspin, "controllerYspin");
  GLADE_HOOKUP_OBJECT (rat__n, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (rat__n, invertY, "invertY");
  GLADE_HOOKUP_OBJECT (rat__n, reverseY, "reverseY");
  GLADE_HOOKUP_OBJECT (rat__n, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (rat__n, label14, "label14");
  GLADE_HOOKUP_OBJECT (rat__n, chanY, "chanY");

  gtk_window_add_accel_group (GTK_WINDOW (rat__n), accel_group);

  return rat__n;
}

GtkWidget*
create_aboutdialog (void)
{
  GtkWidget *aboutdialog;
  GtkWidget *vbox6;
  GtkWidget *label10;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;

  aboutdialog = gtk_dialog_new ();
  gtk_widget_set_size_request (aboutdialog, 242, 180);
  gtk_window_set_title (GTK_WINDOW (aboutdialog), "About");
  gtk_window_set_type_hint (GTK_WINDOW (aboutdialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox6 = GTK_DIALOG (aboutdialog)->vbox;
  gtk_widget_show (vbox6);

  label10 = gtk_label_new ("'ratón'\nMouse -> MIDI Controller\n\nCopyright (C) 2005 Doug Garmon\n\nGPL license");
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (vbox6), label10, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_CENTER);
  gtk_misc_set_padding (GTK_MISC (label10), 4, 4);

  hbuttonbox1 = GTK_DIALOG (aboutdialog)->action_area;
  gtk_widget_show (hbuttonbox1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  button1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button1);
  gtk_dialog_add_action_widget (GTK_DIALOG (aboutdialog), button1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) aboutdialog, "close",
                    G_CALLBACK (on_dialog1_close),
                    NULL);
  g_signal_connect ((gpointer) aboutdialog, "delete_event",
                    G_CALLBACK (on_dialog1_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog, aboutdialog, "aboutdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (aboutdialog, label10, "label10");
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (aboutdialog, button1, "button1");

  return aboutdialog;
}

GtkWidget*
create_customXdialog (void)
{
  GtkWidget *customXdialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox7;
  GtkWidget *hbox10;
  GtkWidget *curveX;
  GtkWidget *vbuttonbox1;
  GtkWidget *curveXsetlinear;
  GtkWidget *curveXsetspline;
  GtkWidget *curveXsetfree;
  GtkWidget *curveXreset;
  GtkWidget *frame1;
  GtkWidget *hbuttonbox2;
  GtkWidget *curveXopen;
  GtkWidget *curveXsaveas;
  GtkWidget *label15;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton_curveX;
  GtkWidget *okbutton1_curveX;

  customXdialog = gtk_dialog_new ();
  gtk_widget_set_size_request (customXdialog, 328, 296);
  gtk_window_set_title (GTK_WINDOW (customXdialog), "Custom X axis curve");
  gtk_window_set_type_hint (GTK_WINDOW (customXdialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (customXdialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox7, TRUE, TRUE, 0);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox10, TRUE, TRUE, 0);

  curveX = gtk_curve_new ();
  gtk_widget_show (curveX);
  gtk_box_pack_start (GTK_BOX (hbox10), curveX, TRUE, TRUE, 0);
  gtk_widget_set_size_request (curveX, 238, 190);
  gtk_curve_set_range (GTK_CURVE (curveX), 0, 127, 0, 127);

  vbuttonbox1 = gtk_vbutton_box_new ();
  gtk_widget_show (vbuttonbox1);
  gtk_box_pack_start (GTK_BOX (hbox10), vbuttonbox1, FALSE, TRUE, 0);

  curveXsetlinear = gtk_button_new_with_mnemonic ("Linear");
  gtk_widget_show (curveXsetlinear);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), curveXsetlinear);
  GTK_WIDGET_SET_FLAGS (curveXsetlinear, GTK_CAN_DEFAULT);

  curveXsetspline = gtk_button_new_with_mnemonic ("Spline");
  gtk_widget_show (curveXsetspline);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), curveXsetspline);
  GTK_WIDGET_SET_FLAGS (curveXsetspline, GTK_CAN_DEFAULT);

  curveXsetfree = gtk_button_new_with_mnemonic ("Free");
  gtk_widget_show (curveXsetfree);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), curveXsetfree);
  GTK_WIDGET_SET_FLAGS (curveXsetfree, GTK_CAN_DEFAULT);

  curveXreset = gtk_button_new_with_mnemonic ("Reset");
  gtk_widget_show (curveXreset);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), curveXreset);
  GTK_WIDGET_SET_FLAGS (curveXreset, GTK_CAN_DEFAULT);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox7), frame1, FALSE, TRUE, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_container_add (GTK_CONTAINER (frame1), hbuttonbox2);

  curveXopen = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (curveXopen);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), curveXopen);
  GTK_WIDGET_SET_FLAGS (curveXopen, GTK_CAN_DEFAULT);

  curveXsaveas = gtk_button_new_from_stock ("gtk-save-as");
  gtk_widget_show (curveXsaveas);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), curveXsaveas);
  GTK_WIDGET_SET_FLAGS (curveXsaveas, GTK_CAN_DEFAULT);

  label15 = gtk_label_new ("File");
  gtk_widget_show (label15);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label15);

  dialog_action_area1 = GTK_DIALOG (customXdialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton_curveX = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton_curveX);
  gtk_dialog_add_action_widget (GTK_DIALOG (customXdialog), cancelbutton_curveX, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton_curveX, GTK_CAN_DEFAULT);

  okbutton1_curveX = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1_curveX);
  gtk_dialog_add_action_widget (GTK_DIALOG (customXdialog), okbutton1_curveX, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1_curveX, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) curveX, "curve_type_changed",
                    G_CALLBACK (on_curveX_curve_type_changed),
                    NULL);
  g_signal_connect ((gpointer) curveX, "configure_event",
                    G_CALLBACK (on_curveX_configure_event),
                    NULL);
  g_signal_connect ((gpointer) curveXsetlinear, "clicked",
                    G_CALLBACK (on_curveXsetlinear_clicked),
                    NULL);
  g_signal_connect ((gpointer) curveXsetspline, "clicked",
                    G_CALLBACK (on_curveXsetspline_clicked),
                    NULL);
  g_signal_connect ((gpointer) curveXsetfree, "clicked",
                    G_CALLBACK (on_curveXsetfree_clicked),
                    NULL);
  g_signal_connect ((gpointer) curveXreset, "clicked",
                    G_CALLBACK (on_curveXreset_clicked),
                    NULL);
  g_signal_connect ((gpointer) curveXopen, "clicked",
                    G_CALLBACK (on_curveXopen_clicked),
                    NULL);
  g_signal_connect ((gpointer) curveXsaveas, "clicked",
                    G_CALLBACK (on_curveXsaveas_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancelbutton_curveX, "clicked",
                    G_CALLBACK (on_cancelbutton_curveX_clicked),
                    NULL);
  g_signal_connect ((gpointer) okbutton1_curveX, "clicked",
                    G_CALLBACK (on_okbutton1_curveX_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (customXdialog, customXdialog, "customXdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (customXdialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (customXdialog, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (customXdialog, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (customXdialog, curveX, "curveX");
  GLADE_HOOKUP_OBJECT (customXdialog, vbuttonbox1, "vbuttonbox1");
  GLADE_HOOKUP_OBJECT (customXdialog, curveXsetlinear, "curveXsetlinear");
  GLADE_HOOKUP_OBJECT (customXdialog, curveXsetspline, "curveXsetspline");
  GLADE_HOOKUP_OBJECT (customXdialog, curveXsetfree, "curveXsetfree");
  GLADE_HOOKUP_OBJECT (customXdialog, curveXreset, "curveXreset");
  GLADE_HOOKUP_OBJECT (customXdialog, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (customXdialog, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (customXdialog, curveXopen, "curveXopen");
  GLADE_HOOKUP_OBJECT (customXdialog, curveXsaveas, "curveXsaveas");
  GLADE_HOOKUP_OBJECT (customXdialog, label15, "label15");
  GLADE_HOOKUP_OBJECT_NO_REF (customXdialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (customXdialog, cancelbutton_curveX, "cancelbutton_curveX");
  GLADE_HOOKUP_OBJECT (customXdialog, okbutton1_curveX, "okbutton1_curveX");

  return customXdialog;
}

GtkWidget*
create_customYdialog (void)
{
  GtkWidget *customYdialog;
  GtkWidget *vbox8;
  GtkWidget *vbox9;
  GtkWidget *hbox11;
  GtkWidget *curveY;
  GtkWidget *vbuttonbox2;
  GtkWidget *customYsetlinear;
  GtkWidget *curveYsetspline;
  GtkWidget *curveYsetfree;
  GtkWidget *curveYreset;
  GtkWidget *frame2;
  GtkWidget *hbuttonbox4;
  GtkWidget *curveYopen;
  GtkWidget *curveYsaveas;
  GtkWidget *label16;
  GtkWidget *hbuttonbox3;
  GtkWidget *cancelbutton_curveY;
  GtkWidget *okbutton_curveY;

  customYdialog = gtk_dialog_new ();
  gtk_widget_set_size_request (customYdialog, 328, 296);
  gtk_window_set_title (GTK_WINDOW (customYdialog), "Custom Y axis curve");
  gtk_window_set_type_hint (GTK_WINDOW (customYdialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox8 = GTK_DIALOG (customYdialog)->vbox;
  gtk_widget_show (vbox8);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox9, TRUE, TRUE, 0);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox11, TRUE, TRUE, 0);

  curveY = gtk_curve_new ();
  gtk_widget_show (curveY);
  gtk_box_pack_start (GTK_BOX (hbox11), curveY, TRUE, TRUE, 0);
  gtk_widget_set_size_request (curveY, 238, 190);
  gtk_curve_set_range (GTK_CURVE (curveY), 0, 127, 0, 127);

  vbuttonbox2 = gtk_vbutton_box_new ();
  gtk_widget_show (vbuttonbox2);
  gtk_box_pack_start (GTK_BOX (hbox11), vbuttonbox2, FALSE, TRUE, 0);

  customYsetlinear = gtk_button_new_with_mnemonic ("Linear");
  gtk_widget_show (customYsetlinear);
  gtk_container_add (GTK_CONTAINER (vbuttonbox2), customYsetlinear);
  GTK_WIDGET_SET_FLAGS (customYsetlinear, GTK_CAN_DEFAULT);

  curveYsetspline = gtk_button_new_with_mnemonic ("Spline");
  gtk_widget_show (curveYsetspline);
  gtk_container_add (GTK_CONTAINER (vbuttonbox2), curveYsetspline);
  GTK_WIDGET_SET_FLAGS (curveYsetspline, GTK_CAN_DEFAULT);

  curveYsetfree = gtk_button_new_with_mnemonic ("Free");
  gtk_widget_show (curveYsetfree);
  gtk_container_add (GTK_CONTAINER (vbuttonbox2), curveYsetfree);
  GTK_WIDGET_SET_FLAGS (curveYsetfree, GTK_CAN_DEFAULT);

  curveYreset = gtk_button_new_with_mnemonic ("Reset");
  gtk_widget_show (curveYreset);
  gtk_container_add (GTK_CONTAINER (vbuttonbox2), curveYreset);
  GTK_WIDGET_SET_FLAGS (curveYreset, GTK_CAN_DEFAULT);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox9), frame2, FALSE, TRUE, 0);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox4);
  gtk_container_add (GTK_CONTAINER (frame2), hbuttonbox4);

  curveYopen = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (curveYopen);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), curveYopen);
  GTK_WIDGET_SET_FLAGS (curveYopen, GTK_CAN_DEFAULT);

  curveYsaveas = gtk_button_new_from_stock ("gtk-save-as");
  gtk_widget_show (curveYsaveas);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), curveYsaveas);
  GTK_WIDGET_SET_FLAGS (curveYsaveas, GTK_CAN_DEFAULT);

  label16 = gtk_label_new ("File");
  gtk_widget_show (label16);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label16);

  hbuttonbox3 = GTK_DIALOG (customYdialog)->action_area;
  gtk_widget_show (hbuttonbox3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_END);

  cancelbutton_curveY = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton_curveY);
  gtk_dialog_add_action_widget (GTK_DIALOG (customYdialog), cancelbutton_curveY, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton_curveY, GTK_CAN_DEFAULT);

  okbutton_curveY = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton_curveY);
  gtk_dialog_add_action_widget (GTK_DIALOG (customYdialog), okbutton_curveY, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton_curveY, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) curveY, "curve_type_changed",
                    G_CALLBACK (on_curveY_curve_type_changed),
                    NULL);
  g_signal_connect ((gpointer) curveY, "configure_event",
                    G_CALLBACK (on_curveY_configure_event),
                    NULL);
  g_signal_connect ((gpointer) customYsetlinear, "clicked",
                    G_CALLBACK (on_customYsetlinear_clicked),
                    NULL);
  g_signal_connect ((gpointer) curveYsetspline, "clicked",
                    G_CALLBACK (on_curveYsetspline_clicked),
                    NULL);
  g_signal_connect ((gpointer) curveYsetfree, "clicked",
                    G_CALLBACK (on_curveYsetfree_clicked),
                    NULL);
  g_signal_connect ((gpointer) curveYreset, "clicked",
                    G_CALLBACK (on_curveYreset_clicked),
                    NULL);
  g_signal_connect ((gpointer) curveYopen, "clicked",
                    G_CALLBACK (on_curveYopen_clicked),
                    NULL);
  g_signal_connect ((gpointer) curveYsaveas, "clicked",
                    G_CALLBACK (on_curveYsaveas_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancelbutton_curveY, "clicked",
                    G_CALLBACK (on_cancelbutton_curveY_clicked),
                    NULL);
  g_signal_connect ((gpointer) okbutton_curveY, "clicked",
                    G_CALLBACK (on_okbutton_curveY_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (customYdialog, customYdialog, "customYdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (customYdialog, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (customYdialog, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (customYdialog, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (customYdialog, curveY, "curveY");
  GLADE_HOOKUP_OBJECT (customYdialog, vbuttonbox2, "vbuttonbox2");
  GLADE_HOOKUP_OBJECT (customYdialog, customYsetlinear, "customYsetlinear");
  GLADE_HOOKUP_OBJECT (customYdialog, curveYsetspline, "curveYsetspline");
  GLADE_HOOKUP_OBJECT (customYdialog, curveYsetfree, "curveYsetfree");
  GLADE_HOOKUP_OBJECT (customYdialog, curveYreset, "curveYreset");
  GLADE_HOOKUP_OBJECT (customYdialog, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (customYdialog, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (customYdialog, curveYopen, "curveYopen");
  GLADE_HOOKUP_OBJECT (customYdialog, curveYsaveas, "curveYsaveas");
  GLADE_HOOKUP_OBJECT (customYdialog, label16, "label16");
  GLADE_HOOKUP_OBJECT_NO_REF (customYdialog, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (customYdialog, cancelbutton_curveY, "cancelbutton_curveY");
  GLADE_HOOKUP_OBJECT (customYdialog, okbutton_curveY, "okbutton_curveY");

  return customYdialog;
}

GtkWidget*
create_opendialog1 (void)
{
  GtkWidget *opendialog1;
  GtkWidget *dialog_vbox2;
  GtkWidget *dialog_action_area2;
  GtkWidget *button2;
  GtkWidget *button3;

  opendialog1 = gtk_file_chooser_dialog_new ("Open", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_modal (GTK_WINDOW (opendialog1), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (opendialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (opendialog1)->vbox;
  gtk_widget_show (dialog_vbox2);

  dialog_action_area2 = GTK_DIALOG (opendialog1)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  button2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (opendialog1), button2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  button3 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button3);
  gtk_dialog_add_action_widget (GTK_DIALOG (opendialog1), button3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button2, "released",
                    G_CALLBACK (on_openfile_cancel),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_openfile_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (opendialog1, opendialog1, "opendialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (opendialog1, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT_NO_REF (opendialog1, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (opendialog1, button2, "button2");
  GLADE_HOOKUP_OBJECT (opendialog1, button3, "button3");

  gtk_widget_grab_default (button3);
  return opendialog1;
}

GtkWidget*
create_savedialog1 (void)
{
  GtkWidget *savedialog1;
  GtkWidget *dialog_vbox3;
  GtkWidget *dialog_action_area3;
  GtkWidget *button4;
  GtkWidget *button5;

  savedialog1 = gtk_file_chooser_dialog_new ("Save", NULL, GTK_FILE_CHOOSER_ACTION_SAVE, NULL);
  gtk_window_set_modal (GTK_WINDOW (savedialog1), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (savedialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (savedialog1)->vbox;
  gtk_widget_show (dialog_vbox3);

  dialog_action_area3 = GTK_DIALOG (savedialog1)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  button4 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button4);
  gtk_dialog_add_action_widget (GTK_DIALOG (savedialog1), button4, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  button5 = gtk_button_new_from_stock ("gtk-save-as");
  gtk_widget_show (button5);
  gtk_dialog_add_action_widget (GTK_DIALOG (savedialog1), button5, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button4, "released",
                    G_CALLBACK (on_savefile_cancel),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_savefile_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (savedialog1, savedialog1, "savedialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (savedialog1, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT_NO_REF (savedialog1, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (savedialog1, button4, "button4");
  GLADE_HOOKUP_OBJECT (savedialog1, button5, "button5");

  gtk_widget_grab_default (button5);
  return savedialog1;
}

GtkWidget*
create_prefsdialog (void)
{
  GtkWidget *prefsdialog;
  GtkWidget *dialog_vbox4;
  GtkWidget *notebook1;
  GtkWidget *notepagegeneral;
  GtkWidget *stdfeedback_button;
  GtkWidget *colorfeedback_button;
  GtkWidget *GlobalPref;
  GtkWidget *notepagex;
  GtkWidget *vbox14;
  GtkWidget *label24;
  GtkWidget *table1;
  GtkObject *xpre_stepnumber_adj;
  GtkWidget *xpre_stepnumber;
  GtkObject *xpre_stepoffset_adj;
  GtkWidget *xpre_stepoffset;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *hseparator2;
  GtkWidget *vbox15;
  GtkWidget *label25;
  GtkWidget *hbox12;
  GtkWidget *label28;
  GtkObject *xpre_randnumber_adj;
  GtkWidget *xpre_randnumber;
  GtkWidget *xaxisPrefs;
  GtkWidget *notepagey;
  GtkWidget *vbox17;
  GtkWidget *label29;
  GtkWidget *table2;
  GtkObject *ypre_stepnumber_adj;
  GtkWidget *ypre_stepnumber;
  GtkObject *ypre_stepoffset_adj;
  GtkWidget *ypre_stepoffset;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *hseparator3;
  GtkWidget *vbox18;
  GtkWidget *label32;
  GtkWidget *hbox13;
  GtkWidget *label33;
  GtkObject *ypre_randnumber_adj;
  GtkWidget *ypre_randnumber;
  GtkWidget *yaxisPrefs;
  GtkWidget *dialog_action_area4;
  GtkWidget *applybutton1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  prefsdialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (prefsdialog), "Preferences");
  gtk_window_set_type_hint (GTK_WINDOW (prefsdialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox4 = GTK_DIALOG (prefsdialog)->vbox;
  gtk_widget_show (dialog_vbox4);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), notebook1, TRUE, TRUE, 0);

  notepagegeneral = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (notepagegeneral);
  gtk_container_add (GTK_CONTAINER (notebook1), notepagegeneral);
  gtk_container_set_border_width (GTK_CONTAINER (notepagegeneral), 12);

  stdfeedback_button = gtk_check_button_new_with_mnemonic ("Send mouse and MIDI feedback to console");
  gtk_widget_show (stdfeedback_button);
  gtk_box_pack_start (GTK_BOX (notepagegeneral), stdfeedback_button, FALSE, FALSE, 0);

  colorfeedback_button = gtk_check_button_new_with_mnemonic ("Feedback in color");
  gtk_widget_show (colorfeedback_button);
  gtk_box_pack_start (GTK_BOX (notepagegeneral), colorfeedback_button, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (colorfeedback_button), 6);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (colorfeedback_button), TRUE);

  GlobalPref = gtk_label_new ("General");
  gtk_widget_show (GlobalPref);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), GlobalPref);

  notepagex = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (notepagex);
  gtk_container_add (GTK_CONTAINER (notebook1), notepagex);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox14);
  gtk_box_pack_start (GTK_BOX (notepagex), vbox14, TRUE, TRUE, 0);

  label24 = gtk_label_new ("Stepped preset");
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (vbox14), label24, FALSE, FALSE, 0);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox14), table1, TRUE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 10);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 4);

  xpre_stepnumber_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  xpre_stepnumber = gtk_spin_button_new (GTK_ADJUSTMENT (xpre_stepnumber_adj), 1, 0);
  gtk_widget_show (xpre_stepnumber);
  gtk_table_attach (GTK_TABLE (table1), xpre_stepnumber, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (xpre_stepnumber), TRUE);

  xpre_stepoffset_adj = gtk_adjustment_new (0, -127, 127, 1, 10, 10);
  xpre_stepoffset = gtk_spin_button_new (GTK_ADJUSTMENT (xpre_stepoffset_adj), 1, 0);
  gtk_widget_show (xpre_stepoffset);
  gtk_table_attach (GTK_TABLE (table1), xpre_stepoffset, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (xpre_stepoffset), TRUE);

  label26 = gtk_label_new ("Number of steps");
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table1), label26, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label26), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new ("Offset");
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table1), label27, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label27), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (notepagex), hseparator2, TRUE, TRUE, 0);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox15);
  gtk_box_pack_start (GTK_BOX (notepagex), vbox15, TRUE, TRUE, 0);

  label25 = gtk_label_new ("Random preset");
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (vbox15), label25, FALSE, FALSE, 0);

  hbox12 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox15), hbox12, TRUE, TRUE, 0);

  label28 = gtk_label_new ("Number of steps");
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox12), label28, FALSE, FALSE, 0);

  xpre_randnumber_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  xpre_randnumber = gtk_spin_button_new (GTK_ADJUSTMENT (xpre_randnumber_adj), 1, 0);
  gtk_widget_show (xpre_randnumber);
  gtk_box_pack_start (GTK_BOX (hbox12), xpre_randnumber, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (xpre_randnumber), TRUE);

  xaxisPrefs = gtk_label_new ("X axis");
  gtk_widget_show (xaxisPrefs);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), xaxisPrefs);

  notepagey = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (notepagey);
  gtk_container_add (GTK_CONTAINER (notebook1), notepagey);

  vbox17 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox17);
  gtk_box_pack_start (GTK_BOX (notepagey), vbox17, TRUE, TRUE, 0);

  label29 = gtk_label_new ("Stepped preset");
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (vbox17), label29, FALSE, FALSE, 0);

  table2 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox17), table2, TRUE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 10);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 4);

  ypre_stepnumber_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  ypre_stepnumber = gtk_spin_button_new (GTK_ADJUSTMENT (ypre_stepnumber_adj), 1, 0);
  gtk_widget_show (ypre_stepnumber);
  gtk_table_attach (GTK_TABLE (table2), ypre_stepnumber, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (ypre_stepnumber), TRUE);

  ypre_stepoffset_adj = gtk_adjustment_new (0, -127, 127, 1, 10, 10);
  ypre_stepoffset = gtk_spin_button_new (GTK_ADJUSTMENT (ypre_stepoffset_adj), 1, 0);
  gtk_widget_show (ypre_stepoffset);
  gtk_table_attach (GTK_TABLE (table2), ypre_stepoffset, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (ypre_stepoffset), TRUE);

  label30 = gtk_label_new ("Number of steps");
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table2), label30, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label30), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  label31 = gtk_label_new ("Offset");
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table2), label31, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label31), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (notepagey), hseparator3, TRUE, TRUE, 0);

  vbox18 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox18);
  gtk_box_pack_start (GTK_BOX (notepagey), vbox18, TRUE, TRUE, 0);

  label32 = gtk_label_new ("Random preset");
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (vbox18), label32, FALSE, FALSE, 0);

  hbox13 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox18), hbox13, TRUE, TRUE, 0);

  label33 = gtk_label_new ("Number of steps");
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox13), label33, FALSE, FALSE, 0);

  ypre_randnumber_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  ypre_randnumber = gtk_spin_button_new (GTK_ADJUSTMENT (ypre_randnumber_adj), 1, 0);
  gtk_widget_show (ypre_randnumber);
  gtk_box_pack_start (GTK_BOX (hbox13), ypre_randnumber, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (ypre_randnumber), TRUE);

  yaxisPrefs = gtk_label_new ("Y axis");
  gtk_widget_show (yaxisPrefs);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), yaxisPrefs);

  dialog_action_area4 = GTK_DIALOG (prefsdialog)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  applybutton1 = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (applybutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefsdialog), applybutton1, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (applybutton1, GTK_CAN_DEFAULT);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefsdialog), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefsdialog), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) stdfeedback_button, "toggled",
                    G_CALLBACK (on_stdfeedback_button_toggled),
                    NULL);
  g_signal_connect ((gpointer) colorfeedback_button, "toggled",
                    G_CALLBACK (on_colorfeedback_button_toggled),
                    NULL);
  g_signal_connect ((gpointer) xpre_stepnumber, "value_changed",
                    G_CALLBACK (on_xpre_stepnumber_value_changed),
                    NULL);
  g_signal_connect ((gpointer) xpre_stepoffset, "value_changed",
                    G_CALLBACK (on_xpre_stepoffset_value_changed),
                    NULL);
  g_signal_connect ((gpointer) xpre_randnumber, "value_changed",
                    G_CALLBACK (on_xpre_randnumber_value_changed),
                    NULL);
  g_signal_connect ((gpointer) ypre_stepnumber, "value_changed",
                    G_CALLBACK (on_ypre_stepnumber_value_changed),
                    NULL);
  g_signal_connect ((gpointer) ypre_stepoffset, "value_changed",
                    G_CALLBACK (on_ypre_stepoffset_value_changed),
                    NULL);
  g_signal_connect ((gpointer) ypre_randnumber, "value_changed",
                    G_CALLBACK (on_ypre_randnumber_value_changed),
                    NULL);
  g_signal_connect ((gpointer) applybutton1, "clicked",
                    G_CALLBACK (on_prefsapply_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancelbutton1, "clicked",
                    G_CALLBACK (on_prefscancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_prefsok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prefsdialog, prefsdialog, "prefsdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (prefsdialog, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (prefsdialog, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (prefsdialog, notepagegeneral, "notepagegeneral");
  GLADE_HOOKUP_OBJECT (prefsdialog, stdfeedback_button, "stdfeedback_button");
  GLADE_HOOKUP_OBJECT (prefsdialog, colorfeedback_button, "colorfeedback_button");
  GLADE_HOOKUP_OBJECT (prefsdialog, GlobalPref, "GlobalPref");
  GLADE_HOOKUP_OBJECT (prefsdialog, notepagex, "notepagex");
  GLADE_HOOKUP_OBJECT (prefsdialog, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (prefsdialog, label24, "label24");
  GLADE_HOOKUP_OBJECT (prefsdialog, table1, "table1");
  GLADE_HOOKUP_OBJECT (prefsdialog, xpre_stepnumber, "xpre_stepnumber");
  GLADE_HOOKUP_OBJECT (prefsdialog, xpre_stepoffset, "xpre_stepoffset");
  GLADE_HOOKUP_OBJECT (prefsdialog, label26, "label26");
  GLADE_HOOKUP_OBJECT (prefsdialog, label27, "label27");
  GLADE_HOOKUP_OBJECT (prefsdialog, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (prefsdialog, vbox15, "vbox15");
  GLADE_HOOKUP_OBJECT (prefsdialog, label25, "label25");
  GLADE_HOOKUP_OBJECT (prefsdialog, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (prefsdialog, label28, "label28");
  GLADE_HOOKUP_OBJECT (prefsdialog, xpre_randnumber, "xpre_randnumber");
  GLADE_HOOKUP_OBJECT (prefsdialog, xaxisPrefs, "xaxisPrefs");
  GLADE_HOOKUP_OBJECT (prefsdialog, notepagey, "notepagey");
  GLADE_HOOKUP_OBJECT (prefsdialog, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (prefsdialog, label29, "label29");
  GLADE_HOOKUP_OBJECT (prefsdialog, table2, "table2");
  GLADE_HOOKUP_OBJECT (prefsdialog, ypre_stepnumber, "ypre_stepnumber");
  GLADE_HOOKUP_OBJECT (prefsdialog, ypre_stepoffset, "ypre_stepoffset");
  GLADE_HOOKUP_OBJECT (prefsdialog, label30, "label30");
  GLADE_HOOKUP_OBJECT (prefsdialog, label31, "label31");
  GLADE_HOOKUP_OBJECT (prefsdialog, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (prefsdialog, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (prefsdialog, label32, "label32");
  GLADE_HOOKUP_OBJECT (prefsdialog, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (prefsdialog, label33, "label33");
  GLADE_HOOKUP_OBJECT (prefsdialog, ypre_randnumber, "ypre_randnumber");
  GLADE_HOOKUP_OBJECT (prefsdialog, yaxisPrefs, "yaxisPrefs");
  GLADE_HOOKUP_OBJECT_NO_REF (prefsdialog, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (prefsdialog, applybutton1, "applybutton1");
  GLADE_HOOKUP_OBJECT (prefsdialog, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (prefsdialog, okbutton1, "okbutton1");

  return prefsdialog;
}

