/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_rat__n (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_customXdialog (void);
GtkWidget* create_customYdialog (void);
GtkWidget* create_opendialog1 (void);
GtkWidget* create_savedialog1 (void);
GtkWidget* create_prefsdialog (void);
